[package]
name = "nfsense"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
ipnet = { version = "2.8.0", features = ["serde"] }
macaddr = { version = "1.0.1", features = ["serde"] }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["full"] }
tower-http = "0.4.4"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
validator = { version = "0.15", features = ["derive"] }
