#!/bin/bash

ask_yes_no() {
  while true; do
    read -rp "$QUESTION (y/n): " yn
    case "$yn" in
      [Yy]) return 0 ;;
      [Nn]) return 1 ;;
      *) echo "Please answer y or n." ;
    esac
  done
}


echo "First Time Setup"
echo "Change keyboard layout if required with 'loadkeys'. example: 'loadkeys de-latin1'"
echo "List interfaces with 'ip a' to find your management interface"
echo "Set a ip with 'ip addr add [ip]/[cidr] dev [interface]'"
echo "Enable interface with 'ip link set [interface] up'"
echo "Set default route with ip with 'ip route add 0.0.0.0/0 via [gateway] dev [interface]'"
echo "The Webinterface should now be available under 'https://[ip]:4444'"
echo "Please Create the interface and route via the Webinterface again and Apply changes to complete the setup"

echo "First Time Setup Complete! Have fun."
rm -f "/root/first-time-setup"
