#!/bin/bash

ask_yes_no() {
  while true; do
    read -rp "$QUESTION (y/n): " yn
    case "$yn" in
      [Yy]) return 0 ;;
      [Nn]) return 1 ;;
      *) echo "Please answer y or n." ;
    esac
  done
}


echo "First Time Setup"
QUESTION="Change the Keyboard layout?"
if ask_yes_no; then
  dpkg-reconfigure keyboard-configuration
  setupcon -k -f
fi

clear
echo "First Time Setup Complete! Have fun."
rm -f "/root/first-time-setup"
